[package]
name = "rboy"
version = "0.1.0"
authors = [
    "mvdnes <git@mathijs.vd-nes.nl>",
    "Tomasz Mikus <mikus.tomasz@gmail.com>"
]
edition = "2021"

[dependencies]
blip_buf = ">=0.1.3"
clap = "4"
cpal = "0.15"
glium = "0.36"
rppal = "0.22.1"
